### ISSUE TITLE
Bug: Crashing on startup with Minecraft 20w12a

### ISSUE THREAD

**Issue by 13rac1** [13rac1/Minecraft-Water-Erosion#14]
Curseforge user [roberooski](https://www.curseforge.com/members/roberooski) reports the following crash. No further information was provided.
```
---- Minecraft Crash Report -------- Minecraft Crash Report ----// Hey, that tickles! Hehehe!
Time: 3/20/20 4:41 PMDescription: Initializing game
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at net.minecraft.class_2378.method_10237(class_2378.java:81) at net.minecraft.class_2378.method_10238(class_2378.java:125) at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663) at net.minecraft.class_2378.<clinit>(class_2378.java:124) at net.minecraft.class_2966.method_12851(class_2966.java:38) at net.minecraft.class_310.<init>(class_310.java:393) at net.minecraft.client.main.Main.main(Main.java:166) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [erosion.mixins.json:FluidBlockMixin] from phase [DEFAULT] in config [erosion.mixins.json] FAILED during APPLY at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643) at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356) ... 20 moreCaused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> erosion.mixins.json:FluidBlockMixin -> Apply Methods -> (Lnet/minecraft/class_2248$class_2251;)V:<init> -> Transform Descriptor -> desc=Lnet/minecraft/class_2248$class_2251;] at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:490) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:523) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:509) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:381) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ... 20 moreCaused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraft.class_2248$class_2251 at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:938) at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:909) at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethodDescriptor(MixinTargetContext.java:953) at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformDescriptor(MixinTargetContext.java:865) at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:447) ... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Render threadStacktrace: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at net.minecraft.class_2378.method_10237(class_2378.java:81) at net.minecraft.class_2378.method_10238(class_2378.java:125) at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663) at net.minecraft.class_2378.<clinit>(class_2378.java:124) at net.minecraft.class_2966.method_12851(class_2966.java:38) at net.minecraft.class_310.<init>(class_310.java:393)
-- Initialization --Details:Stacktrace: at net.minecraft.client.main.Main.main(Main.java:166) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
-- System Details --Details: Minecraft Version: 20w12a Minecraft Version ID: 20w12a Operating System: Mac OS X (x86_64) version 10.13.6 Java Version: 1.8.0_74, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 89422664 bytes (85 MB) / 167772160 bytes (160 MB) up to 2147483648 bytes (2048 MB) CPUs: 4 JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M Fabric Mods:  fabric: Fabric API 0.5.5+build.311-1.16 fabric-api-base: Fabric API Base 0.1.2+b7f9825dd1 fabric-biomes-v1: Fabric Biomes (v1) 0.2.1+b7d52fa5d1 fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea89d1 fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825dd1 fabric-containers-v0: Fabric Containers (v0) 0.1.7+d249f7b6d1 fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825dd1 fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825dd1 fabric-dimensions-v1: fabric-dimensions-v1 0.3.1+d249f7b6d1 fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+04b99794d1 fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825dd1 fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.10+d249f7b6d1 fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d6d1 fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.6+2f56dff2d1 fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+5b8a535ad1 fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d6d1 fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.4+9421522dd1 fabric-networking-v0: Fabric Networking (v0) 0.1.9+d249f7b6d1 fabric-object-builders-v0: Fabric Object Builders (v0) 0.2.1+ce6dd838d1 fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d6d1 fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.8+d249f7b6d1 fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.11+2f56dff2d1 fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.26+d249f7b6d1 fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a60d1 fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825dd1 fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed9d1 fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+53410490d1 fabric-rendering-v1: Fabric Rendering (v1) 0.1.1+d249f7b6d1 fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.12+5b8a535ad1 fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd91580d1 fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba7d1 fabricloader: Fabric Loader 0.7.8+build.189 minecraft: Minecraft 1.16-alpha.20.12.a water-erosion: Water Erosion 1.0.2 wi-zoom: WI Zoom v1.1-MC20w12a Launched Version: fabric-loader-0.7.8+build.189-20w12a Backend library: LWJGL version 3.2.1 build 12 Backend API: NO CONTEXT GL Caps:  Using VBOs: Yes Is Modded: Definitely; Client brand changed to 'fabric' Type: Client (map_client.txt) CPU: <unknown>
```

Steps to reproduce have not been provided, so I can only guess the cause/solution. I suspect the problem is there is no Water Erosion build for 20w12a (at this time) https://www.curseforge.com/minecraft/mc-mods/water-erosion/files/all?filter-status=1&filter-game-version=2020709689%3A7751

*Note: I've deleted the associated comment from the Curseforge Mod page, because the log message is excessively long and bugs should be filed here.*

**Comment by 13rac1** [comment]
I'm closing this for now, since this snapshot is not supported yet. I'm working towards finishing 1.1.0 instead of bumping the snapshots.
